package com.example.pojo;

public class ExpertsDatabase {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experts_database.fault_id
     *
     * @mbg.generated Fri Sep 13 14:14:34 CST 2019
     */
    private Integer faultId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experts_database.fault_type
     *
     * @mbg.generated Fri Sep 13 14:14:34 CST 2019
     */
    private String faultType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experts_database.fault_msg
     *
     * @mbg.generated Fri Sep 13 14:14:34 CST 2019
     */
    private String faultMsg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experts_database.fault_id
     *
     * @return the value of experts_database.fault_id
     *
     * @mbg.generated Fri Sep 13 14:14:34 CST 2019
     */
    public Integer getFaultId() {
        return faultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experts_database.fault_id
     *
     * @param faultId the value for experts_database.fault_id
     *
     * @mbg.generated Fri Sep 13 14:14:34 CST 2019
     */
    public void setFaultId(Integer faultId) {
        this.faultId = faultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experts_database.fault_type
     *
     * @return the value of experts_database.fault_type
     *
     * @mbg.generated Fri Sep 13 14:14:34 CST 2019
     */
    public String getFaultType() {
        return faultType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experts_database.fault_type
     *
     * @param faultType the value for experts_database.fault_type
     *
     * @mbg.generated Fri Sep 13 14:14:34 CST 2019
     */
    public void setFaultType(String faultType) {
        this.faultType = faultType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experts_database.fault_msg
     *
     * @return the value of experts_database.fault_msg
     *
     * @mbg.generated Fri Sep 13 14:14:34 CST 2019
     */
    public String getFaultMsg() {
        return faultMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experts_database.fault_msg
     *
     * @param faultMsg the value for experts_database.fault_msg
     *
     * @mbg.generated Fri Sep 13 14:14:34 CST 2019
     */
    public void setFaultMsg(String faultMsg) {
        this.faultMsg = faultMsg;
    }
}