package com.example.mapper;

import com.example.pojo.ExpertsDatabase;
import com.example.pojo.ExpertsDatabaseExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface ExpertsDatabaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts_database
     *
     * @mbg.generated Fri Sep 13 14:14:34 CST 2019
     */
    long countByExample(ExpertsDatabaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts_database
     *
     * @mbg.generated Fri Sep 13 14:14:34 CST 2019
     */
    int deleteByExample(ExpertsDatabaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts_database
     *
     * @mbg.generated Fri Sep 13 14:14:34 CST 2019
     */
    int deleteByPrimaryKey(Integer faultId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts_database
     *
     * @mbg.generated Fri Sep 13 14:14:34 CST 2019
     */
    int insert(ExpertsDatabase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts_database
     *
     * @mbg.generated Fri Sep 13 14:14:34 CST 2019
     */
    int insertSelective(ExpertsDatabase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts_database
     *
     * @mbg.generated Fri Sep 13 14:14:34 CST 2019
     */
    List<ExpertsDatabase> selectByExample(ExpertsDatabaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts_database
     *
     * @mbg.generated Fri Sep 13 14:14:34 CST 2019
     */
    ExpertsDatabase selectByPrimaryKey(Integer faultId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts_database
     *
     * @mbg.generated Fri Sep 13 14:14:34 CST 2019
     */
    int updateByExampleSelective(@Param("record") ExpertsDatabase record, @Param("example") ExpertsDatabaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts_database
     *
     * @mbg.generated Fri Sep 13 14:14:34 CST 2019
     */
    int updateByExample(@Param("record") ExpertsDatabase record, @Param("example") ExpertsDatabaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts_database
     *
     * @mbg.generated Fri Sep 13 14:14:34 CST 2019
     */
    int updateByPrimaryKeySelective(ExpertsDatabase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts_database
     *
     * @mbg.generated Fri Sep 13 14:14:34 CST 2019
     */
    int updateByPrimaryKey(ExpertsDatabase record);
}